# Generated by Django 6.1.1 on 2026-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('por_confirmar', 'Por Confirmar'), ('pendiente', 'Pendiente (Cocina)'), ('preparacion', 'En Preparación'), ('listo', 'Listo'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='por_confirmar', max_length=20),
        ),
    ]
