# Generated by Django 6.1.1 on 2026-09-16 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente (Cocina)'), ('preparacion', 'En Preparación'), ('entregado', 'Entregado (En Mesa)'), ('pagado', 'Pagado (Cerrado)'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
